server:
    undertow:
        accesslog:
            enabled: false
            dir: /var/logs/${server.port}

logging:
    level:
        com.baayso: DEBUG

spring:
    redis:
        database: 0
        host: 192.168.1.222
        port: 6379
        password:
        jedis:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1ms
                min-idle: 0
        timeout: 0ms
    datasource:
        url: jdbc:mysql://192.168.1.222:3306/springbootdemo?useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
        druid:
            initial-size: 1
            min-idle: 1
            max-active: 8
            # 如果用Oracle则把poolPreparedStatements配置为true，MySQL可以配置为false。分库分表较多的数据库建议配置为false。
            poolPreparedStatements: false
            filter:
                stat:
                  enabled: true
                  log-slow-sql: true
                wall:
                    enabled: true
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                reset-enable: false
                login-username: baayso
                login-password: baayso
            web-stat-filter:
                enabled: true
                url-pattern: /*
                exclusions: /druid,/druid/*

mybatis-plus:
    global-config:
        # 是否自动刷新 Mapper 对应的 XML 文件，默认不自动刷新。更改 XML 文件后，无需再次重启工程。该配置不建议在生产环境打开。
        refresh: true
