server:
    port: 8888
    # context-path: /springboot
    compression:
        enabled: true
        mime-types: text/html,application/xml,application/json,application/javascript,text/css,text/plain
        min-response-size: 1024
    ssl:
        enabled: true
        key-store: classpath:config/sample.jks
        key-store-password: secret
        key-password: password

spring:
    profiles:
        active: dev
    application:
        admin:
            enabled: false
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        joda-date-time-format: yyyy-MM-dd HH:mm:ss
        # serialization-inclusion: NON_NULL
        default-property-inclusion: NON_NULL
        time-zone: Asia/Shanghai
    mvc:
        date-format: yyyy-MM-dd HH:mm:ss
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        enabled: true
        cache: false
        request-context-attribute: request
        template-loader-path: classpath:/templates/

#mybatis:
#    config-location: classpath:config/mybatis-config.xml
#    mapper-locations: classpath*:mybatis/**/*.xml
#
#mapper:
#    mappers:
#        - com.baayso.springboot.common.CommonMapper
#    not-empty: false
#    identity: MYSQL
#
#pagehelper:
#    helperDialect: mysql
#    # 分页参数合理化，默认 false
#    reasonable: false
#    # 支持通过Mapper接口参数来传递分页参数
#    supportMethodsArguments: true
#    params: count=countSql
