server:
    port: 8888
    # context-path: /springboot
    compression:
        enabled: true
        mime-types: text/html,application/xml,application/json,application/javascript,text/css,text/plain
        min-response-size: 1024
    ssl:
        enabled: true
        key-store: classpath:config/sample.jks
        key-store-password: secret
        key-password: password
    undertow:
        accesslog:
            enabled: false
            dir: /var/logs

spring:
    profiles:
        active: dev
    application:
        admin:
            enabled: true
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        joda-date-time-format: yyyy-MM-dd HH:mm:ss
    mvc:
        date-format: yyyy-MM-dd HH:mm:ss
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        enabled: true
        cache: false
        request-context-attribute: request

