server:
    undertow:
        accesslog:
            enabled: false
            dir: /var/logs/${server.port}

logging:
    level:
        com.baayso: DEBUG

spring:
    redis:
        database: 0
        host: 192.168.1.222
        port: 6379
        password:
        pool:
            max-active: 8
            max-idle: 8
            max-wait: -1
            min-idle: 0
        timeout: 0
    datasource:
        url: jdbc:mysql://192.168.1.222:3306/springbootdemo?useSSL=false
        username: root
        password: root
        druid:
            initial-size: 1
            min-idle: 1
            max-active: 8
            # 如果用Oracle则把poolPreparedStatements配置为true，MySQL可以配置为false。分库分表较多的数据库建议配置为false。
            poolPreparedStatements: false
            filter:
                stat:
                  enabled: true
                  log-slow-sql: true
                wall:
                    enabled: true
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                reset-enable: false
                login-username: baayso
                login-password: baayso
            web-stat-filter:
                enabled: true
                url-pattern: /*
                exclusions: /druid,/druid/*
