server:
    undertow:
        accesslog:
            enabled: false
            dir: /var/logs/${server.port}

logging:
    level:
        com.baayso: DEBUG

spring:
    redis:
        database: 0
        host: localhost
        port: 6379
        password:
        pool:
            max-active: 8
            max-idle: 8
            max-wait: -1
            min-idle: 0
        timeout: 0

datasource:
    name: druidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springbootdemo?useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource # 使用druid数据源
    initialSize: 1
    minIdle: 1
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxOpenPreparedStatements: 20
    filters: stat,wall
    removeAbandoned: true
    removeAbandonedTimeoutMillis: 300000
    logAbandoned: true
