server:
    undertow:
        accesslog:
            enabled: false
            dir: /var/logs/${server.port}

logging:
    path: /var/logs
    file: spring-boot-demo-${server.port}.log
    level:
        com.baayso: INFO

spring:
    devtools:
        livereload:
            enabled: false
        restart:
            enabled: false
        remote:
            debug:
                enabled: false
            restart:
                enabled: false
    redis:
        database: 8
        host: localhost
        port: 6379
        password:
        pool:
            max-active: 2048
            max-idle: 10
            max-wait: -1
            min-idle: 0
        timeout: 0

datasource:
    name: druidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springbootdemo
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource # 使用druid数据源
    initialSize: 10
    minIdle: 10
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxOpenPreparedStatements: 20
    filters: stat,wall
    removeAbandoned: true
    removeAbandonedTimeoutMillis: 300000
    logAbandoned: true
